server:
  port: 8765

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: currency-exchange-service
          uri: lb://currency-exchange-service
          predicates:
            - Path=/api/v1/currency-exchange/**

        - id: currency-calculation-service
          uri: lb://currency-calculation-service
          predicates:
            - Path=/api/v1/currency-calculation/**
